### ISSUE TITLE
Data_Processing/Classifications/CamCAT : missing Trigger_ID once merged

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#10]
Example : Site S33

Once CamCAT output provided ("se.asia.2.classifications.database.eon.von") was merged with dtbs, the species table included empty Trigger_ID.

**Comment by RossPitman** [comment]
This issue occurs when we provide classifications from more than just the survey we're trying to merge. This is because Camera CATalogue makes it very difficult to separate out surveys, and rather subsets data by date. This isn't a major issue, but requires IDS to subset those data out; this is now implemented as of version 1.721 by doing the following:

`tidyr::drop_na(TriggerID)`

within the ct_jn_clssfctns_dt_trggr_tbl function within ct_utility_funs.R
