### ISSUE TITLE
MAIN-38 ⁃ Issues with camera activty records in databases

### ISSUE THREAD

**Issue by PhilipFaure** [pantheracorp/PantheraIDS_Issues#157]
Some databases have problems with their cameras active tables. Possibly, this is causing an issue with the naming of images when data gets processed (i.e. the images are skipped because the camact table is reading that there should not be any images for a given date). 

An example would be from S7_2014 (server database) where there seem to be multiple Camera2's on the same day (i.e. 2014-07-02) for Station10. Similarly, Station1 (still S7_2014) has multiple records for the same date (Fig. 1).

![Screenshot 2020-09-10 at 12 24 52 (2)](https://user-images.githubusercontent.com/24668143/92719260-31245d00-f363-11ea-9d17-f787535920f8.png) 
_**Figure 1.** S7_2014 server-based database showing multiple cameras for the same camera on the same day._

Looking into other databases, S15_2015 has images between 2015-09-15 and 2015-09-22 which weren't renamed correctly for Station2, Camera1 and Camera2 (Fig. 3). This is due to the the cameras active sheet saying that these cameras were inactive (i.e. 0) for those days. Consequently, IDS skipped these images because the user told it that there are no images for those days at those locations (see highlighted rows in IDS Table, Fig. 3).

![Screenshot 2020-09-10 at 12 36 51 (2)](https://user-images.githubusercontent.com/24668143/92719900-23bba280-f364-11ea-9afc-4ffecb7d01de.png)
_**Figure 2.** Screenshot showing the IDS table on the left, wrongly named images in the middle (from server), and server image names with missing image filenames._

Recommended actions (feel free to add anything):

1. Check whether the SQL code in tables wrangles the data from the server to IDS correctly.
1. Find a solution for the images that are wrongly named on the server.

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-38) by [Unito](https://www.unito.io/learn-more)

**Comment by PhilipFaure** [comment]
@RossPitman @Shannon-Dubay 

...don't want you guys to feel left out from this beauty!

**Comment by Shannon-Dubay** [comment]
Some additional information that may be helpful:
Local images for S7_2014 are on Master7, while local images for S15_2015 are on Master1. However, in both cases the raw data are not true "raw" data- it is in the renamed format of IDS' predecessor. Master7 is with Lauren, who I believe is on leave for a week. Master1 is on campus in the office. 

Unfortunately I wasn't able to check the local images to compare with the server images, but I was able to check local databases- not sure if it they are the most up to date, but shouldn't matter for now.

**S15_2015 (incorrectly "processed" images due to 0 in camera active table for days in which camera was active):**
If I understand correctly, the "FileName" column refers to the name of the image before it was processed. So, I checked the "FileName" for a few of the images Phil pointed out that are on the server but with an old name format, and they are not included in the database at all, which is the same as the server-based database, I believe? Within the "FileName_New" column, I can see the gap in images that Phil refers to. So it appears the local database is similar to the server (as expected). 

**S7_2014 (incorrectly "processed" images due to incorrect Camera1 and Camera2 inputs):**
Checked the CA table and the trigger table and it also shows the same as the server (as expected).

So, the above suggestion of _checking whether the SQL code in tables wrangles the data from the server to IDS correctly_ is likely unnecessary. 

Further thoughts:
- Whatever fixes we make to these images should be implemented on the server-based images and the local ones- there are still instances were southern Africa uses the Master hard drives to export, etc.
- What is the easiest way to check if there are more surveys which have "unprocessed" file names? I suppose it will have to be an interrogation of the images, because its difficult to determine if there is missing data from the databases if you don't know what you're missing!

**Comment by RossPitman** [comment]
Folks I don't think these duplicate records make any difference to further use in IDS. I can't see if this would cause any issues down the line. @PhilipFaure can you recall why we were concerned about this? 

IDS bases its processing protocol on the cameras active and raw images, so there's not much else we can do. We certainly won't be fixing historical datasets. 

Putting this on ice for now until we identify an actual serious problem.

**Comment by PhilipFaure** [comment]
I don't see any issues in IDS, I think this is more a database problem, which likely comes from the cameras active input file which had mistakes in. Consequently, images that were actually there on a given day are not processed because the cameras active file had some mistakes in. This is how I understand it...

**Comment by Shannon-Dubay** [comment]
I think while these examples seem to be database-specific, these examples can be used to inform any 'checks' of the data within IDS during processing, or within the Validation module. It would be best to incorporate these checks within the Processing stage so that the issue can be flagged as early as possible. 

In this case, as Phil mentions in his first post, there are multiple Camera2's on the same day for one station. Also, a specific camera is labeled as Camera1 AND as Camera2 for its station. These are things we can potentially have IDS check when the user loads in their Camera Active, and if anything is incorrect, an informative popup will alert them to the error (perhaps by specifying the station/cameraID/date of concern). It is important for the user to fix these CA issues as it created issues with the renaming/processing of large chucks of images, as Phil witnessed, which is not very obvious to the user.

Another problem that Phil noticed that leads to missing images is a 0 (indicating inactive) in the camera active sheet for a camera on a particular day, when the camera was in fact active and took images. I'm not sure if there is any way to instigate a check/cross reference for this, but if so, it would also be very helpful so that images aren't skipped.

**Comment by Shannon-Dubay** [comment]
Just to record another example of CA issues that we could put checks into IDS for:

S5_2014:

Station22: each day there is 1 Camera1 (CAM43187) and 2 different Camera2s (CAM40866 and CAM43187)... one of which you'll notice is the same CameraID as Camera1 (see screenshot below). Upon interrogation of the data, an impact of this mistake is that some images taken by CAM43187 were assigned "Camera2" when they should be "Camera1". 
![image](https://user-images.githubusercontent.com/48274721/94811591-ddeb7a80-03f5-11eb-92c3-f77a51f542c1.png)

The same happens at Station23 of this same survey, but worse: 
1 Camera1 and 4 Camera2s, one of which is the same CameraID as Camera1 (just as above).
![image](https://user-images.githubusercontent.com/48274721/94816497-33c32100-03fc-11eb-883e-fb6658e1712c.png)

Station20 is another example.

All examples provided by Hannah, the CB Master student looking at spottie densities.
