### ISSUE TITLE
"Run IDS" results in "ERROR: cannot open the connection" without internet connection

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#168]
I know we have come across this issue in the past, although I don't believe it was posted to GitHub (I can't find a post about it). It has been mentioned on the forum previously [here](https://pantheraids.org/forum.html?p=post%2Fautomatic-disconnection-from-server-10471387%3Fpid%3D1311316328), and more recently by Marike [here](https://pantheraids.org/forum.html?p=post%2Frun-ids-results-in-error-cannot-open-the-connection-11103812%3Fpid%3D1319511267).

IDS fails to start, seemingly linked to internet connectivity- users can only start IDS if they are connected to the internet. Marike noticed this using alpha v2.23.891, but not beta v. 2.21.884. She updated her beta yesterday and now also sees the issue in beta v.2.26.894. 

On Marike's forum post @kacoster mentions a fix has been made- is this fix supposed to be included in the current beta version (v.2.26.894)? If so, the fix needs to be looked at again. 
If the fix hasn't been pushed to beta yet, my apologies for posting when it wasn't necessary, and we will wait the next IDS push!

**Comment by RossPitman** [comment]
@kacoster – please look into this as I think it's related to the tracker? Maybe??

**Comment by kacoster** [comment]
@RossPitman This Issue is related to the non-existing ('**pages/body/ui/pantheracam_assts_rgstr_body_ui.R**') that is being loaded in the **pantheraids_ui.R** script. I recall you highlighted that the **pantheracam_assts_rgstr_body_ui.R** script is nolonger in use. After some test I can confirm that **v2.23.891** alpha and **v.2.26.894** beta has that issue. The next update should solve this issue.
