### ISSUE TITLE
Dtbs not mapping in Data Explorer/Maps

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#39]
**S40_2018** (Lope_Ivindo) and **S403_2018** (GKE) give the following error when trying to map from the server:
"Error: $ operator is invalid for atomic vectors"

The log says the following:
Warning in evalq(as.numeric(DateTimeOriginal), <environment>) :
  NAs introduced by coercion
Warning in evalq(as.numeric(DateTimeOriginal), <environment>) :
  NAs introduced by coercion
Error in .local(obj, ...) :
  cannot derive coordinates from non-numeric matrix
Error in sum(sapply(label, function(x) { :
  invalid 'type' (list) of argument
Warning: Error in : $ operator is invalid for atomic vectors
  98: renderWidget
  97: transform
  96: func
  94: f
  93: Reduce
  84: do
  83: hybrid_chain
  82: origRenderFunc
  81: output$dt_explrr_map_ct_mp
   1: runApp
Error in .local(obj, ...) :
  cannot derive coordinates from non-numeric matrix

**Comment by Shannon-Dubay** [comment]
**S3_2017** also not mapping correctly- no error in map area on the screen, just a grey area where the map should be.
The log says the following:
Warning in evalq(as.numeric(X), <environment>) :
  NAs introduced by coercion
Warning in evalq(as.numeric(Y), <environment>) :
  NAs introduced by coercion
Error in .local(obj, ...) : NA values in coordinates

**Comment by RossPitman** [comment]
The reason for S40 and S403 is because there isn't any species and individual data on the server. The reason for S3 is because all the X and Y field are NA. S3_2017 should not be like this, and will have to be repaired server-side. Looking at S3_2017 local dtbs, I see the X and Y field are also NA, so the problem occurred locally. Can you please check your versions of S3_2017 to see if you have data in the X and Y columns?

**Comment by Shannon-Dubay** [comment]
Yes, I have an old local version of S3_2017 on my computer (from Jan 2019) that has information in the X and Y columns- can I send it here or teams rather?

**Comment by RossPitman** [comment]
S3_2017 repaired. Closing issue.
