### ISSUE TITLE
Several buttons don´t work

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#4]
Buttons that don´t work for me: 1) download tables, 2) Maps in Data Explorer Section, 3) when looking at an image in Data Processing/Camera Trapping/Classify I hit right click-Open Image, it doesn´t Open the image in the browser, 4) Report issue, 5)Request Feature.

I´m a PC user.

**Comment by RossPitman** [comment]
1) The maps button in Data Explorer is currently disabled. 

2) Right clicking on an image to open it is likely a browser issue. It would when I do it on Safari.

3) Please explain what happens when clicking the "Report Issue" and "Request Feature" buttons? Does anything get printed to the R console? These buttons have been tested on Mac and Windows, and have been shown to work. I suspect we might be seeing a browser issue here again. Please confirm what browser you're using, and whether it is up to date? Thanks, Roberto! Appreciate it!

**Comment by rsalom** [comment]
It doesn´t show anything on the R console. A window tries to open but immediately closes. I use Google Chrome and it should be up to date.

 I opened IDS on Chrome, and tried it there and it worked!
